#!/bin/bash
GROUP=$(whiptail --inputbox "Enter group name:" 8 50 --title "Add Group" 3>&1 1>&2 2>&3)
if [ $? = 0 ]; then
    if groupadd "$GROUP"; then
        whiptail --msgbox " Group '$GROUP' added successfully" 8 50
    else
        whiptail --msgbox "Failed to add group '$GROUP'." 8 50
    fi
fi
