#!/bin/bash
USERNAME=$(whiptail --inputbox "Enter new username:" 10 60 3>&1 1>&2 2>&3)
[ $? -ne 0 ] && exit 0
if id "$USERNAME" &>/dev/null; then
    whiptail --msgbox "'$USERNAME' already exists!" 10 60
else
    useradd "$USERNAME" && whiptail --msgbox "'$USERNAME' added successfully" 10 60
fi
