#!/bin/bash
GROUP=$(whiptail --inputbox "Enter group name to delete:" 8 50 --title "Delete Group" 3>&1 1>&2 2>&3)
if [ $? = 0 ]; then
    if groupdel "$GROUP"; then
        whiptail --msgbox "Group '$GROUP' deleted successfully" 8 50
    else
        whiptail --msgbox "Failed to delete group '$GROUP'." 8 50
    fi
fi
