#!/bin/bash
USERNAME=$(whiptail --inputbox "Enter username to delete:" 10 60 3>&1 1>&2 2>&3)
[ $? -ne 0 ] && exit 0
if id "$USERNAME" &>/dev/null; then
    userdel "$USERNAME"
    whiptail --msgbox "'$USERNAME' deleted successfully" 10 60
else
    whiptail --msgbox "Error! '$USERNAME' not found" 10 60
fi
