#!/bin/bash
USERNAME=$(whiptail --inputbox "Enter username to disable:" 10 60 3>&1 1>&2 2>&3)
[ $? -ne 0 ] && exit 0

usermod -L "$USERNAME" && whiptail --msgbox "User '$USERNAME' disabled successfully." 10 60
